### ISSUE TITLE
Return a 500 Internal Server Error when building and deploying with Zeit Now

### ISSUE THREAD

**Issue by hugo-s29** [hugos29dev/the-Project-Alpha#1]
Hello,

Can you help me,
I wanted to deploy my project with **Zeit Now** but it doesn't seem to work well.
When we go to the [website](https://theprojectalpha.hugos29.now.sh/), we see a _500 Internal Server Error Code_.

I searched for a long time to see why I can't access it.

The project uses **NextJS 9**, and **API routes** in **Typescript**.
It is inspired by this [blog post](https://zeit.co/guides/deploying-next-and-mysql-with-now/).

Bye,
Hugo

**Comment by iam-abbas** [comment]
Hey Hugo, I will try to fix it 😃

**Comment by hugo-s29** [comment]
Thank @iam-abbas, I'll assign this to you.

**Comment by iam-abbas** [comment]
I found the issue, you never linked any database

**Comment by hugo-s29** [comment]
The database is linked in the .env file (template.env) and with the lib/db.ts file. It works on my computer but not on Zeit Now. I think the problem must not be there.

**Comment by iam-abbas** [comment]
Did you add your database env secrets to now.json?

**Comment by hugo-s29** [comment]
Hi,
I've tried to put environment variables in the now.json file but it doesn't seems to work... 

Bye, 
Hugo

**Comment by hugo-s29** [comment]
Hi,
I've resolved the problem I had.
Thanks for your help,
Hugo

**Comment by hugo-s29** [comment]
@all-contributors please add @iam-abbas for infra
